-- Create tables for channel content management

-- Content posts table
CREATE TABLE public.channel_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_type TEXT NOT NULL, -- district_review, restaurant, prices, visa_guide, apartment_week, news
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  images TEXT[],
  status TEXT DEFAULT 'draft', -- draft, scheduled, published, failed
  scheduled_at TIMESTAMP WITH TIME ZONE,
  published_at TIMESTAMP WITH TIME ZONE,
  telegram_message_id BIGINT,
  ai_generated BOOLEAN DEFAULT false,
  source_data JSONB, -- original data used for AI generation
  engagement_stats JSONB, -- views, reactions, etc.
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- District reviews table
CREATE TABLE public.district_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  district TEXT NOT NULL UNIQUE,
  description TEXT,
  avg_rent_1br NUMERIC,
  avg_rent_2br NUMERIC,
  avg_rent_3br NUMERIC,
  infrastructure_score INTEGER, -- 1-10
  expat_friendly_score INTEGER, -- 1-10
  nightlife_score INTEGER, -- 1-10
  family_score INTEGER, -- 1-10
  tips TEXT[],
  popular_places JSONB, -- restaurants, cafes, gyms
  last_review_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- News sources tracking
CREATE TABLE public.news_sources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_name TEXT NOT NULL,
  source_url TEXT NOT NULL,
  last_scraped_at TIMESTAMP WITH TIME ZONE,
  articles_count INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Parsed news articles
CREATE TABLE public.news_articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id BIGINT REFERENCES public.news_sources(id),
  original_title TEXT NOT NULL,
  original_content TEXT,
  translated_title TEXT,
  translated_content TEXT,
  original_url TEXT,
  published_date TIMESTAMP WITH TIME ZONE,
  is_processed BOOLEAN DEFAULT false,
  is_posted BOOLEAN DEFAULT false,
  relevance_score INTEGER, -- AI-determined relevance for expats
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Content schedule templates
CREATE TABLE public.content_schedule (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day_of_week INTEGER, -- 0-6 (Sunday-Saturday), NULL for daily
  post_time TIME NOT NULL,
  post_type TEXT NOT NULL,
  template TEXT, -- template for AI generation
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.channel_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.district_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.news_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.news_articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_schedule ENABLE ROW LEVEL SECURITY;

-- RLS policies (public access for admin)
CREATE POLICY "Allow all access to channel_posts" ON public.channel_posts FOR ALL USING (true);
CREATE POLICY "Allow all access to district_reviews" ON public.district_reviews FOR ALL USING (true);
CREATE POLICY "Allow all access to news_sources" ON public.news_sources FOR ALL USING (true);
CREATE POLICY "Allow all access to news_articles" ON public.news_articles FOR ALL USING (true);
CREATE POLICY "Allow all access to content_schedule" ON public.content_schedule FOR ALL USING (true);

-- Insert default district data for HCMC
INSERT INTO public.district_reviews (district, description, avg_rent_1br, avg_rent_2br, infrastructure_score, expat_friendly_score, nightlife_score, family_score) VALUES
('District 1', 'Центр города, деловой район', 15000000, 25000000, 9, 8, 10, 5),
('District 2', 'Thao Dien - главный экспат-район', 12000000, 20000000, 8, 10, 7, 9),
('District 3', 'Модный район с кафе и ресторанами', 10000000, 18000000, 8, 8, 8, 7),
('District 7', 'Phu My Hung - корейский район', 10000000, 16000000, 9, 9, 5, 10),
('Binh Thanh', 'Развивающийся район рядом с центром', 8000000, 14000000, 7, 7, 6, 7),
('Thu Duc', 'Новый город, Tech Park', 7000000, 12000000, 6, 6, 4, 8),
('Phu Nhuan', 'Местный колорит, хорошая еда', 8000000, 13000000, 7, 6, 6, 7);

-- Insert default news sources
INSERT INTO public.news_sources (source_name, source_url, is_active) VALUES
('VNExpress', 'https://vnexpress.net', true),
('Tuoi Tre', 'https://tuoitre.vn', true),
('Saigoneer', 'https://saigoneer.com', true);

-- Insert default content schedule
INSERT INTO public.content_schedule (day_of_week, post_time, post_type, template, is_active) VALUES
(NULL, '08:00', 'morning_digest', 'Утренний дайджест: новости + квартира дня', true),
(NULL, '13:00', 'district_review', 'Район дня: обзор района с ценами', true),
(NULL, '19:00', 'evening_entertainment', 'Вечерняя подборка: куда пойти', true),
(1, '10:00', 'apartment_week', 'Квартира недели: подробный обзор', true),
(5, '12:00', 'prices_update', 'Актуальные цены: аренда, еда, транспорт', true);